apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dokan-api-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/auth-url: "http://auth-service.default.svc.cluster.local:3000/auth/_check"
    nginx.ingress.kubernetes.io/auth-method: "POST"
spec:
  rules:
    - host: dokan.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 3000
          - path: /categories
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 3000